### ISSUE TITLE
Crash on setting GPU copy mode to graphic buffer with G620S Android phone

### ISSUE THREAD

**Issue by M-a-r-k** [Rakashazi/emu-ex-plus-alpha#53]
I'm testing Snes9x EX on a Huawei G620S phone (Qualcomm Snapdragon 410 MSM8916, Adreno 306, Android 4.4.4). The GPU driver reports its renderer as "Adreno (TM) 306" and version as "OpenGL ES 3.0 V@84.0 AU@04.04.04.157.009 (CL@)". For OpenGL 1.1 version is reported as "OpenGL ES-CM 1.1"

After launching the emulator but before loading a game, I can change GPU Copy Mode to Graphic Buffer without the emulator crashing. There is this line in adb logcat output when I do that:
E/qdmemalloc(28949): unrecognized pixel format: 0x60f469e7

When I then load a game the emulator crashes. Alternatively, after loading a game if I then open the settings menu and tap to set GPU Copy Mode to Graphic Buffer the emulator crashes then. adb logcat output on doing that is below. There doesn't seem to be any specific indication as to the problem, it just reports that many processes have died. One time the crash seemed to lock up the entire phone, so perhaps this is actually a GPU driver bug.

This isn't a big problem; the default Auto setting works fine so the solution would be "don't do that". But I figure reporting it won't hurt.

```
E/qdmemalloc(29901): unrecognized pixel format: 0x60f4c9e7
I/ActivityManager(  863): Process com.google.android.gms.wearable (pid 29243) has died.
I/ActivityManager(  863): Process android.process.acore (pid 29123) has died.
I/ActivityManager(  863): Process com.android.email (pid 29140) has died.
I/ActivityManager(  863): Process com.android.vending (pid 29408) has died.
I/ActivityManager(  863): Process com.android.settings (pid 29295) has died.
D/WifiService(  863): Client connection lost with reason: 4
I/ActivityManager(  863): Process com.huawei.android.hwouc (pid 29824) has died.
I/ActivityManager(  863): Process com.huawei.wifieapsimplmn (pid 29767) has died.
I/ActivityManager(  863): Process com.huawei.android.mewidget (pid 29092) has died.
F/ProcessStats(  863): Starting service ServiceState{423868b8 com.android.smspush.WapPushManager pkg=com.android.smspush proc=423868b8} without owner
F/ProcessStats(  863): Starting service ServiceState{41e32de0 com.google.android.backup.BackupTransportService pkg=com.google.android.backuptransport proc=41e32de0} without owner
I/ActivityManager(  863): Process com.huawei.wifihotspot (pid 29780) has died.
I/ActivityManager(  863): Process com.huawei.android.wfdft (pid 29753) has died.
D/CountryDetector(  863): No listener is left
I/ActivityManager(  863): Process com.google.android.gms (pid 29190) has died.
F/ProcessStats(  863): Starting service ServiceState{423868b8 com.android.smspush.WapPushManager pkg=com.android.smspush proc=423868b8} without owner
F/ProcessStats(  863): Starting service ServiceState{41e32de0 com.google.android.backup.BackupTransportService pkg=com.google.android.backuptransport proc=41e32de0} without owner
I/ActivityManager(  863): Process com.android.mms (pid 29807) has died.
I/ActivityManager(  863): Process com.huawei.systemmanager (pid 29676) has died.
F/ProcessStats(  863): Starting service ServiceState{423868b8 com.android.smspush.WapPushManager pkg=com.android.smspush proc=423868b8} without owner
F/ProcessStats(  863): Starting service ServiceState{41e32de0 com.google.android.backup.BackupTransportService pkg=com.google.android.backuptransport proc=41e32de0} without owner
E/JavaBinder(  863): !!! FAILED BINDER TRANSACTION !!!
W/InputDispatcher(  863): channel '42aa9050 com.huawei.android.launcher/com.huawei.android.launcher.Launcher (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher(  863): channel '42aa9050 com.huawei.android.launcher/com.huawei.android.launcher.Launcher (server)' ~ Channel is unrecoverably broken and will be disposed!
I/ActivityManager(  863): Process com.huawei.flashlight.openlightservice (pid 29882) has died.
I/ActivityManager(  863): Process com.huawei.flashlight (pid 29869) has died.
I/ActivityManager(  863): Process com.huawei.DiagReboot (pid 29022) has died.
I/WindowState(  863): WIN DEATH: Window{42aa9050 u0 com.huawei.android.launcher/com.huawei.android.launcher.Launcher}
W/InputDispatcher(  863): Attempted to unregister already unregistered input channel '42aa9050 com.huawei.android.launcher/com.huawei.android.launcher.Launcher (server)'
D/WifiService(  863): Client connection lost with reason: 4
E/JavaBinder(  863): !!! FAILED BINDER TRANSACTION !!!
E/JavaBinder(  863): !!! FAILED BINDER TRANSACTION !!!
E/JavaBinder(  863): !!! FAILED BINDER TRANSACTION !!!
W/ActivityManager(  863): Scheduling restart of crashed service com.huawei.DiagReboot/.DiagService in 1000ms
I/ActivityManager(  863): Process com.droidmjt.droidsounde (pid 29843) has died.
E/JavaBinder(  863): !!! FAILED BINDER TRANSACTION !!!
E/JavaBinder(  863): !!! FAILED BINDER TRANSACTION !!!
E/JavaBinder(  863): !!! FAILED BINDER TRANSACTION !!!
I/ServiceManager(  235): service 'dataCollector' died
I/ServiceManager(  235): service 'com.huawei.systemmanager.preventmode.PreventModeService' died
I/ServiceManager(  235): service 'com.huawei.permissionmanager.service.holdservice' died
I/ServiceManager(  235): service 'com.huawei.netassistant.binder.notificationcallbackbinder' died
I/ServiceManager(  235): service 'com.huawei.netassistant.service.netassistantservice' died
I/ServiceManager(  235): service 'com.huawei.harassmentinterception.service.HarassmentInterceptionService' died
I/ActivityManager(  863): Process android.process.media (pid 29076) has died.
W/ActivityManager(  863): Scheduling restart of crashed service com.android.providers.media/.MtpService in 31444ms
I/ActivityManager(  863): Process com.huawei.android.launcher (pid 29010) has died.
I/ActivityManager(  863): Process com.google.process.gapps (pid 29163) has died.
F/ActivityManager(  863): Service ServiceRecord{42e72b88 u0 com.google.android.gms/.clearcut.service.ClearcutLoggerService} in process ProcessRecord{4218eb78 29163:com.google.process.gapps/u0a7} not same as in map: null
D/GpsLocationProvider(  863): GPS status listener died
D/WifiService(  863): Client connection lost with reason: 4
D/QC_RIL_OEM_HOOK( 1285): The connection to the service got disconnected unexpectedly!
D/LocationManagerService(  863): Location listener died
D/LocationManagerService(  863): Location listener died
I/LocationManagerService(  863): remove 42903430
W/ActivityManager(  863): Scheduling restart of crashed service com.google.android.gms/.gcm.GcmService in 41374ms
I/ActivityManager(  863): Process com.huawei.systemmanager:service (pid 29660) has died.
W/ActivityManager(  863): Scheduling restart of crashed service com.huawei.systemmanager/.widget.OnekeyCleanService in 51362ms
W/ActivityManager(  863): Scheduling restart of crashed service com.huawei.systemmanager/.service.MainService in 61361ms
W/ActivityManager(  863): Scheduling restart of crashed service com.huawei.systemmanager/.preventmode.PreventModeService in 71361ms
W/ActivityManager(  863): Scheduling restart of crashed service com.huawei.systemmanager/com.huawei.permission.HoldService in 81361ms
W/ActivityManager(  863): Scheduling restart of crashed service com.huawei.systemmanager/com.huawei.harassmentinterception.service.HarassmentInterceptionService in 91361ms
D/LocationManagerService(  863): provider request: passive ProviderRequest[ON interval=0]
I/LocationManagerService(  863): remove 4295b710
D/LocationManagerService(  863): provider request: passive ProviderRequest[ON interval=0]
W/ActivityManager(  863): Scheduling restart of crashed service com.huawei.systemmanager/.power.BgPowerManagerService in 101360ms
W/ActivityManager(  863): Scheduling restart of crashed service com.huawei.systemmanager/com.huawei.netmanager.service.NetControllService in 111360ms
W/ActivityManager(  863): Scheduling restart of crashed service com.huawei.systemmanager/.optimize.smcs.SMCSService in 121360ms
I/ActivityManager(  863): Process com.google.android.inputmethod.latin (pid 29343) has died.
W/ActivityManager(  863): Scheduling restart of crashed service com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME in 131355ms
I/ActivityManager(  863): Process com.qualcomm.qcrilmsgtunnel (pid 29364) has died.
W/ActivityManager(  863): Scheduling restart of crashed service com.qualcomm.qcrilmsgtunnel/.QcrilMsgTunnelService in 141332ms
I/ActivityManager(  863): Process com.google.android.gms.persistent (pid 29213) has died.
W/ActivityManager(  863): Scheduling restart of crashed service com.google.android.gms/com.google.android.location.internal.server.GoogleLocationService in 151320ms
W/ActivityManager(  863): Scheduling restart of crashed service com.google.android.gms/com.google.android.location.internal.PendingIntentCallbackService in 161319ms
W/ActivityManager(  863): Scheduling restart of crashed service com.google.android.gms/.deviceconnection.service.DeviceConnectionServiceBroker in 171319ms
W/ActivityManager(  863): Scheduling restart of crashed service com.google.android.gms/com.google.android.location.internal.GoogleLocationManagerService in 181318ms
W/ActivityManager(  863): Scheduling restart of crashed service com.google.android.gms/.common.stats.GmsCoreStatsService in 191318ms
W/ActivityManager(  863): Scheduling restart of crashed service com.google.android.gms/com.google.android.contextmanager.service.ContextManagerService in 201318ms
W/ActivityManager(  863): Scheduling restart of crashed service com.google.android.gms/com.google.android.location.geofencer.service.GeofenceProviderService in 211317ms
W/ActivityManager(  863): Scheduling restart of crashed service com.google.android.gms/com.google.android.location.fused.service.FusedProviderService in 221316ms
W/ActivityManager(  863): Scheduling restart of crashed service com.google.android.gms/com.google.android.location.geocode.GeocodeService in 231316ms
W/ActivityManager(  863): Scheduling restart of crashed service com.google.android.gms/com.google.android.location.fused.FusedLocationService in 241315ms
I/ActivityManager(  863): Process com.android.nfc:handover (pid 28998) has died.
W/ActivityManager(  863): Scheduling restart of crashed service com.android.nfc/.handover.HandoverService in 0ms
I/ActivityManager(  863): Start proc com.android.nfc:handover for service com.android.nfc/.handover.HandoverService: pid=29979 uid=1027 gids={41027, 3002, 3001, 1028, 1015, 1023, 3003}
W/InputMethodManagerService(  863): Session failed to close due to remote exception
W/InputMethodManagerService(  863): android.os.DeadObjectException
W/InputMethodManagerService(  863): 	at android.os.BinderProxy.transact(Native Method)
W/InputMethodManagerService(  863): 	at com.android.internal.view.IInputMethodSession$Stub$Proxy.finishSession(IInputMethodSession.java:292)
W/InputMethodManagerService(  863): 	at com.android.server.InputMethodManagerService.finishSessionLocked(InputMethodManagerService.java:1451)
W/InputMethodManagerService(  863): 	at com.android.server.InputMethodManagerService.clearClientSessionLocked(InputMethodManagerService.java:1442)
W/InputMethodManagerService(  863): 	at com.android.server.InputMethodManagerService.clearCurMethodLocked(InputMethodManagerService.java:1468)
W/InputMethodManagerService(  863): 	at com.android.server.InputMethodManagerService.onServiceDisconnected(InputMethodManagerService.java:1487)
W/InputMethodManagerService(  863): 	at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:1156)
W/InputMethodManagerService(  863): 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1170)
W/InputMethodManagerService(  863): 	at android.os.Handler.handleCallback(Handler.java:733)
W/InputMethodManagerService(  863): 	at android.os.Handler.dispatchMessage(Handler.java:95)
W/InputMethodManagerService(  863): 	at android.os.Looper.loop(Looper.java:136)
W/InputMethodManagerService(  863): 	at com.android.server.ServerThread.initAndLoop(SystemServer.java:1371)
W/InputMethodManagerService(  863): 	at com.android.server.SystemServer.main(SystemServer.java:1734)
W/InputMethodManagerService(  863): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/InputMethodManagerService(  863): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/InputMethodManagerService(  863): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
W/InputMethodManagerService(  863): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:711)
W/InputMethodManagerService(  863): 	at dalvik.system.NativeStart.main(Native Method)
W/InputMethodManagerService(  863): Session failed to close due to remote exception
W/InputMethodManagerService(  863): android.os.DeadObjectException
W/InputMethodManagerService(  863): 	at android.os.BinderProxy.transact(Native Method)
W/InputMethodManagerService(  863): 	at com.android.internal.view.IInputMethodSession$Stub$Proxy.finishSession(IInputMethodSession.java:292)
W/InputMethodManagerService(  863): 	at com.android.server.InputMethodManagerService.finishSessionLocked(InputMethodManagerService.java:1451)
W/InputMethodManagerService(  863): 	at com.android.server.InputMethodManagerService.clearClientSessionLocked(InputMethodManagerService.java:1442)
W/InputMethodManagerService(  863): 	at com.android.server.InputMethodManagerService.clearCurMethodLocked(InputMethodManagerService.java:1468)
W/InputMethodManagerService(  863): 	at com.android.server.InputMethodManagerService.onServiceDisconnected(InputMethodManagerService.java:1487)
W/InputMethodManagerService(  863): 	at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:1156)
W/InputMethodManagerService(  863): 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1170)
W/InputMethodManagerService(  863): 	at android.os.Handler.handleCallback(Handler.java:733)
W/InputMethodManagerService(  863): 	at android.os.Handler.dispatchMessage(Handler.java:95)
W/InputMethodManagerService(  863): 	at android.os.Looper.loop(Looper.java:136)
W/InputMethodManagerService(  863): 	at com.android.server.ServerThread.initAndLoop(SystemServer.java:1371)
W/InputMethodManagerService(  863): 	at com.android.server.SystemServer.main(SystemServer.java:1734)
W/InputMethodManagerService(  863): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/InputMethodManagerService(  863): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/InputMethodManagerService(  863): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
W/InputMethodManagerService(  863): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:711)
W/InputMethodManagerService(  863): 	at dalvik.system.NativeStart.main(Native Method)
W/InputDispatcher(  863): channel '426fc9b0 com.explusalpha.Snes9x/com.imagine.BaseActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher(  863): channel '426fc9b0 com.explusalpha.Snes9x/com.imagine.BaseActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
I/ActivityManager(  863): Process com.explusalpha.Snes9x (pid 29901) has died.
I/WindowState(  863): WIN DEATH: Window{426fc9b0 u0 com.explusalpha.Snes9x/com.imagine.BaseActivity}
W/ActivityManager(  863): Force removing ActivityRecord{42e93b08 u0 com.explusalpha.Snes9x/com.imagine.BaseActivity t293}: app died, no saved state
W/MediaFocusControl(  863):   AudioFocus   audio focus client died
W/InputDispatcher(  863): Attempted to unregister already unregistered input channel '426fc9b0 com.explusalpha.Snes9x/com.imagine.BaseActivity (server)'
I/MediaFocusControl(  863): AudioFocus  removeFocusStackEntry(): removing entry for android.os.BinderProxy@4224c3b8
W/MessageQueue( 1091): Handler (android.media.AudioManager$FocusEventHandlerDelegate$1) {4353f3b0} sending message to a Handler on a dead thread
W/MessageQueue( 1091): java.lang.RuntimeException: Handler (android.media.AudioManager$FocusEventHandlerDelegate$1) {4353f3b0} sending message to a Handler on a dead thread
W/MessageQueue( 1091): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:320)
W/MessageQueue( 1091): 	at android.os.Handler.enqueueMessage(Handler.java:626)
W/MessageQueue( 1091): 	at android.os.Handler.sendMessageAtTime(Handler.java:595)
W/MessageQueue( 1091): 	at android.os.Handler.sendMessageDelayed(Handler.java:566)
W/MessageQueue( 1091): 	at android.os.Handler.sendMessage(Handler.java:503)
W/MessageQueue( 1091): 	at android.media.AudioManager$1.dispatchAudioFocusChange(AudioManager.java:2322)
W/MessageQueue( 1091): 	at android.media.IAudioFocusDispatcher$Stub.onTransact(IAudioFocusDispatcher.java:57)
W/MessageQueue( 1091): 	at android.os.Binder.execTransact(Binder.java:404)
W/MessageQueue( 1091): 	at dalvik.system.NativeStart.run(Native Method)
V/WindowManager(  863): moveTaskToTop mTaskChanged:true
I/ActivityManager(  863): Start proc com.huawei.android.launcher for activity com.huawei.android.launcher/.Launcher: pid=29991 uid=10069 gids={50069, 1028, 1015, 1023}
D/ActivityThread(29979): handleBindApplication:com.android.nfc:handover
D/ActivityThread(29979): setTargetHeapUtilization:0.75
D/ActivityThread(29979): setTargetHeapMinFree:2097152
D/InputDispatcher(  863): Dispatch frozen.  Waiting some more.
I/InputReader(  863): Reconfiguring input devices.  changes=0x00000004
I/InputReader(  863): Device reconfigured: id=8, name='synaptics_dsx_i2c', size 720x1280, orientation 0, mode 1, display id 0
D/InputDispatcher(  863): Dispatch frozen.  Waiting some more.
I/ActivityManager(  863): Config changes=480 {0.85 ?mcc?mnc en_GB ldltr sw360dp w360dp h615dp 320dpi nrml long port finger -keyb/v/h -nav/h suim:1 s.272}
D/InputDispatcher(  863): Dispatch frozen.  Waiting some more.
D/InputDispatcher(  863): Dispatch frozen.  Waiting some more.
V/AudioManager( 1256): isSpeakerphoneOn...
V/SMCSAMSHelper(  863): SMCSAMSHelper.addSTPEvent: cost 2 ms end.
V/SMCSAMSHelper(  863): SMCSAMSHelper.smartTrimProcessPackageResume: cost time 75 ms end.
D/InputDispatcher(  863): Dispatch frozen.  Waiting some more.
V/WindowManager(  863): setFocusedApp update app ops, mTaskChanged set to:false
D/PhoneGlobals( 1256): updateProximitySensorMode: lock already released.
I/ActivityManager(  863): Start proc com.huawei.DiagReboot for service com.huawei.DiagReboot/.DiagService: pid=30003 uid=1000 gids={41000, 3002, 3001, 1028, 1015, 1023, 3003, 3006, 1021, 3004, 3005, 1000, 3009, 1010}
D/Tethering(  863): Exception adding default nw to upstreamIfaceTypes: java.lang.NullPointerException
I/IconMerger( 1091): onMeasure, width =48
I/IconMerger( 1091): mSpaceWidth =825
I/IconMerger( 1091): onMeasure, width =48
I/IconMerger( 1091): mSpaceWidth =825
I/IconMerger( 1091): onMeasure, width =265
D/InputDispatcher(  863): Dispatch frozen.  Waiting some more.
D/InputDispatcher(  863): Dispatch frozen.  Waiting some more.
I/IconMerger( 1091): mSpaceWidth =825
D/ActivityThread(29991): handleBindApplication:com.huawei.android.launcher
D/ActivityThread(29991): setTargetHeapUtilization:0.75
D/ActivityThread(29991): setTargetHeapMinFree:2097152
D/Tethering(  863): checkDunExisted: selection=numeric = '' and carrier_enabled = 1
I/IconMerger( 1091): Visible children =1, N =1, width =240
D/InputDispatcher(  863): Dispatch frozen.  Waiting some more.
D/StatusBar.NetworkController( 1091): onReceive action=android.intent.action.CONFIGURATION_CHANGED
D/InputDispatcher(  863): Dispatch frozen.  Waiting some more.
E/StubController(  863): service = null
D/ActivityThread(30003): handleBindApplication:com.huawei.DiagReboot
D/ActivityThread(30003): setTargetHeapUtilization:0.75
D/ActivityThread(30003): setTargetHeapMinFree:2097152
E/CursorWindow(  863):  CursorWindow::createFromParcel  ashmemFd=200, ssize_t=2097152  UNKNOWN_ERROR=1096410857
E/CursorWindow(  863):  CursorWindow::createFromParcel
D/Tethering(  863): requiredApn: MOBILE_HIPRI
D/SystemUi.PhoneStatusBar( 1091): PhoneStatusBar recever configuration changed load resources
V/AudioManager(  863): getStreamVolume  treamType: 2
V/AudioManager(  863): isStreamMute   streamType: 2
D/BluetoothManagerService(  863): Message: 20
D/BluetoothManagerService(  863): Added callback: android.bluetooth.IBluetoothManagerCallback$Stub$Proxy@41cb20a0:true
D/SystemUi.PhoneStatusBar( 1091): update ToolBox when the Configuration is changed.
V/AudioManager(  863): getRingerMode...
V/AudioManager(  863): getStreamVolume  treamType: 3
V/AudioManager(  863): isStreamMute   streamType: 3
V/AudioManager(  863): getStreamVolume  treamType: 4
V/AudioManager(  863): isStreamMute   streamType: 4
V/AudioManager(  863): getStreamVolume  treamType: 0
V/AudioManager(  863): isStreamMute   streamType: 0
V/MediaPlayerService(  257): decode(47, 80480, 6641)
D/PRDrmPlugIn(  255): PRDrmPlugin::onInitialize, uniqueId = 4724
D/PRDrmPlugIn(  255): PRDrmPlugin::onSetOnInfoListener: starts! uniqueId = 4724
D/PRDrmPlugIn(  255): PRDrmPlugin::onSetOnInfoListener: ends!
D/PRDrmPlugIn(  255): PRDrmPlugin::onTerminate, uniqueId = 4724
V/MediaPlayerService(  257): player type = 3
V/MediaPlayerFactory(  257):  create StagefrightPlayer
I/ExtendedUtils(  257): AV Sync late margin : Intended=40ms Using=0ms
V/AudioCache(  257): notify(0xb796b880, 8, 0, 0)
V/AudioCache(  257): ignored
D/Utils   (  257): printFileName fd(48) -> /system/app/NfcDNci.apk
D/PRDrmPlugIn(  255): PRDrmPlugin::onInitialize, uniqueId = 5561
D/PRDrmPlugIn(  255): PRDrmPlugin::onSetOnInfoListener: starts! uniqueId = 5561
D/PRDrmPlugIn(  255): PRDrmPlugin::onSetOnInfoListener: ends!
D/PRDrmPlugIn(  255): PRDrmPlugin::onTerminate, uniqueId = 5561
V/MediaExtractor(  257): Autodetected media content as 'video/qc-ogg' with confidence 0.80
V/MediaExtractor(  257): MediaExtractor::Create mime = video/qc-ogg
D/ExtendedUtils(  257): Try creating ExtendedExtractor
D/ExtendedUtils(  257): default extractor is NULL, return extended extractor
E/MM_OSAL (  257): FileSource::FileSource
E/MM_OSAL (  257): FileSource::FileSource m_bEveryThingOK 1
D/DiagReboot(30003): Service onCreate
E/MM_OSAL (  257): MM_File_Create failed .Efs Error No -1 , File Name /data/mmosal_logmask.cfg , Mode 0
V/AwesomePlayer(  257): mBitrate = 64000 bits/sec
V/MediaPlayerService(  257): prepare
V/MediaPlayerService(  257): wait for prepare
V/AwesomePlayer(  257): onPrepareAsyncEvent.
E/DiagReboot(30003): JNI Trying to load libDiagSettings
I/OMXCodec(  257): Successfully allocated OMX node 'OMX.google.vorbis.decoder'
D/OMXCodec(  257): Successfully allocated OMX node 'OMX.google.vorbis.decoder'
I/AwesomePlayer(  257): Could not offload audio decode, try pcm offload
V/AudioCache(  257): notify(0xb796b880, 5, 0, 0)
V/AudioCache(  257): ignored
V/AudioCache(  257): notify(0xb796b880, 1, 0, 0)
V/AudioCache(  257): prepared
V/AudioCache(  257): wait - success
V/MediaPlayerService(  257): start
D/AudioPlayer(  257): start of Playback, useOffload 0
E/Diag_Lib(30003): JNI_OnLoad called
E/Diag_Lib(30003): JNI Diag_LSM_Init call succeeded
D/DiagReboot(30003): Service onStart
V/AudioCache(  257): open(16000, 1, 0x0, 1, 4)
V/AudioCache(  257): notify(0xb796b880, 6, 0, 0)
V/AudioCache(  257): ignored
V/MediaPlayerService(  257): wait for playback complete
V/AudioCache(  257): write(0xb79fe2a8, 2048)
V/AudioCache(  257): memcpy(0xb29c0000, 0xb79fe2a8, 2048)
V/AudioCache(  257): write(0xb79fe2a8, 2048)
V/AudioCache(  257): memcpy(0xb29c0800, 0xb79fe2a8, 2048)
V/AudioCache(  257): write(0xb79fe2a8, 2048)
V/AudioCache(  257): memcpy(0xb29c1000, 0xb79fe2a8, 2048)
V/AudioCache(  257): write(0xb79fe2a8, 2048)
V/AudioCache(  257): memcpy(0xb29c1800, 0xb79fe2a8, 2048)
V/AudioCache(  257): write(0xb79fe2a8, 2048)
V/AudioCache(  257): memcpy(0xb29c2000, 0xb79fe2a8, 2048)
V/AudioCache(  257): write(0xb79fe2a8, 2048)
V/AudioCache(  257): memcpy(0xb29c2800, 0xb79fe2a8, 2048)
V/AudioCache(  257): write(0xb79fe2a8, 2048)
V/AudioCache(  257): memcpy(0xb29c3000, 0xb79fe2a8, 2048)
V/AudioCache(  257): write(0xb79fe2a8, 2048)
V/AudioCache(  257): memcpy(0xb29c3800, 0xb79fe2a8, 2048)
V/AudioCache(  257): write(0xb79fe2a8, 2048)
V/AudioCache(  257): memcpy(0xb29c4000, 0xb79fe2a8, 2048)
V/AudioCache(  257): write(0xb79fe2a8, 2048)
V/AudioCache(  257): memcpy(0xb29c4800, 0xb79fe2a8, 2048)
V/AudioCache(  257): write(0xb79fe2a8, 2048)
V/AudioCache(  257): memcpy(0xb29c5000, 0xb79fe2a8, 2048)
E/MMParserExtractor(  257): FileSource::FILE_SOURCE_DATA_END 
V/AudioCache(  257): write(0xb79fe2a8, 2048)
V/AudioCache(  257): memcpy(0xb29c5800, 0xb79fe2a8, 2048)
V/AudioCache(  257): write(0xb79fe2a8, 2048)
V/AudioCache(  257): memcpy(0xb29c6000, 0xb79fe2a8, 2048)
V/AudioCache(  257): write(0xb79fe2a8, 1280)
V/AudioCache(  257): memcpy(0xb29c6800, 0xb79fe2a8, 1280)
V/AwesomePlayer(  257): MEDIA_PLAYBACK_COMPLETE
V/AudioCache(  257): notify(0xb796b880, 2, 0, 0)
V/AudioCache(  257): playback complete
V/AudioCache(  257): wait - success
V/AudioCache(  257): notify(0xb796b880, 7, 0, 0)
V/MediaPlayerService(  257): return size 27904, sampleRate=16000, channelCount = 1, format = 1
V/AudioCache(  257): ignored
D/AudioPlayer(  257): Pause Playback at 872000
V/AudioCache(  257): notify(0xb796b880, 8, 0, 0)
V/AudioCache(  257): ignored
D/AudioPlayer(  257): reset: mPlaying=0 mReachedEOS=1 useOffload=0
E/StubController(29991): service = null
E/CursorWindow(29991):  CursorWindow::createFromParcel  ashmemFd=65, ssize_t=2097152  UNKNOWN_ERROR=1096410857
E/CursorWindow(29991):  CursorWindow::createFromParcel
W/HwLauncher(29991): <NetInteractiveStart> NIParamError
V/HwWidgetFactory(29991): : successes to get AllImpl object and return....
E/StubController(29991): service = null
E/CursorWindow( 1091):  CursorWindow::createFromParcel  ashmemFd=92, ssize_t=2097152  UNKNOWN_ERROR=1096410857
E/CursorWindow( 1091):  CursorWindow::createFromParcel
E/CursorWindow( 1091):  CursorWindow::createFromParcel  ashmemFd=92, ssize_t=2097152  UNKNOWN_ERROR=1096410857
E/CursorWindow( 1091):  CursorWindow::createFromParcel
D/HwTransition(29991): hwtransition version = 0.2.11, targetView = com.huawei.android.launcher.Workspace{41df9790 V.ED.... ......I. 0,0-0,0 #7f070049 app:id/workspace}
W/TAG     (29991): newWidth = 1440
I/Launcher (29991): sAllThreadsUri=content://mms-sms/conversations?simple=true
W/HwLauncher(29991): Model setCouldUpdatePackage(false) at the begining of loadWorkspaceOptimize
E/StubController(29991): service = null
E/CursorWindow(29991):  CursorWindow::createFromParcel  ashmemFd=73, ssize_t=2097152  UNKNOWN_ERROR=1096410857
E/CursorWindow(29991):  CursorWindow::createFromParcel
E/StubController(29991): service = null
E/StubController(29991): service = null
E/CursorWindow(29991):  CursorWindow::createFromParcel  ashmemFd=75, ssize_t=2097152  UNKNOWN_ERROR=1096410857
E/CursorWindow(29991):  CursorWindow::createFromParcel
D/InputDispatcher(  863): Dispatch frozen.  Waiting some more.
D/InputDispatcher(  863): Dispatch frozen.  Waiting some more.
I/HwLauncher(29991): Model  onReceive intent=Intent { act=android.intent.action.SIM_STATE_CHANGED flg=0x10 (has extras) }
I/ActivityManager(  863): Start proc com.huawei.android.thememanager for content provider com.huawei.android.thememanager/.downloader.ThemeManagerProvider: pid=30034 uid=10075 gids={50075, 1028, 1015, 3003, 1023}
D/ActivityThread(30034): handleBindApplication:com.huawei.android.thememanager
D/ActivityThread(30034): setTargetHeapUtilization:0.75
D/ActivityThread(30034): setTargetHeapMinFree:2097152
E/StubController(29991): service = null
E/StubController(29991): service = null
E/StubController(29991): service = null
I/ActivityThread(29991): com.huawei.android.launcher query other app provider, pkg:com.huawei.android.thememanager uid:10075, send to pg
E/StubController(30034): service = null
E/CursorWindow(29991):  CursorWindow::createFromParcel  ashmemFd=80, ssize_t=2097152  UNKNOWN_ERROR=1096410857
E/CursorWindow(29991):  CursorWindow::createFromParcel
E/CursorWindow(29991):  CursorWindow::createFromParcel  ashmemFd=80, ssize_t=2097152  UNKNOWN_ERROR=1096410857
E/CursorWindow(29991):  CursorWindow::createFromParcel
W/HwLauncher(29991): Launcher.Utilities  InvocationTargetException: not set hw_wallpaper_scrollable in hw_default.xml
D/InputDispatcher(  863): Dispatch frozen.  Waiting some more.
D/InputDispatcher(  863): Dispatch frozen.  Waiting some more.
D/InputDispatcher(  863): Dispatch frozen.  Waiting some more.
I/Adreno-EGL(29991): <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LNX.LA.3.7.2.1_RB1.04.04.04.157.009_msm8916_32_LNX.LA.3.7.2.1_RB1__release_AU ()
I/Adreno-EGL(29991): OpenGL ES Shader Compiler Version: E031.24.02.07
I/Adreno-EGL(29991): Build Date: 07/30/14 Wed
I/Adreno-EGL(29991): Local Branch: mybranch3995205
I/Adreno-EGL(29991): Remote Branch: quic/LNX.LA.3.7.2.1_rb1
I/Adreno-EGL(29991): Local Patches: NONE
I/Adreno-EGL(29991): Reconstruct Branch: AU_LINUX_ANDROID_LNX.LA.3.7.2.1_RB1.04.04.04.157.009 +  NOTHING
D/InputDispatcher(  863): Dispatch frozen.  Waiting some more.
D/OpenGLRenderer(29991): Enabling debug mode 0
D/InputDispatcher(  863): Dispatch frozen.  Waiting some more.
D/InputDispatcher(  863): Dispatch frozen.  Waiting some more.
D/InputDispatcher(  863): Dispatch frozen.  Waiting some more.
D/InputDispatcher(  863): Dispatch frozen.  Waiting some more.
I/ActivityManager(  863): Displayed com.huawei.android.launcher/.Launcher: +3s218ms
D/CubicBezierInterpolator(  863): CubicBezierInterpolator  mControlPoint1x = 0.5, mControlPoint1y = 0.15, mControlPoint2x = 0.55, mControlPoint2y = 0.95
D/CubicBezierInterpolator(  863): CubicBezierInterpolator  mControlPoint1x = 0.5, mControlPoint1y = 0.15, mControlPoint2x = 0.55, mControlPoint2y = 0.95
I/WindowManager(  863): Screen frozen for +3s57ms due to Window{42888540 u0 com.huawei.android.launcher/com.huawei.android.launcher.Launcher}
W/InputMethodManagerService(  863): Got RemoteException sending setActive(false) notification to pid 29901 uid 10140
V/RenderScript(29991): Application requested CPU execution
D/dalvikvm(29991): GC_CONCURRENT freed 3944K, 45% free 7415K/13332K, paused 6ms+4ms, total 77ms
D/dalvikvm(29991): WAIT_FOR_CONCURRENT_GC blocked 47ms
V/RenderScript(29991): 0x63436f40 Launching thread(s), CPUs 4
E/StubController(29991): service = null
```

**Comment by Rakashazi** [comment]
Graphic Buffer is a private API so it's not guaranteed to work. In the best case the functions will return errors but in sometimes they have other unexpected effects like crashing or freezing the app. I've added a warning prompt if trying to set it on a device that's not in the app's whitelist.
